name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: ./.node-version

      - run: corepack enable
      - run: npm ci

      - run: npm run build
      - run: npm run lint

  changesets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version-file: ./.node-version

      - run: corepack enable
      - run: npm ci

      - run: npx changeset status --since=main
